### PR TITLE
fix metadata for seasons and episodes - fix extended artwork

### PR DESCRIPTION
**Pull request by marcelveldt**
Hi @logi85,

I've put some work in fixing the metadata for the listitems. Now all data should be returned correctly at all levels using the correct container content and sort options.

Also I have replaced the tmdb implementation (which was failing anyway) with a lookup from my skin helper service. If the user enabled the artwork lookups, all artwork (including clearart etc) is retrieved from the skinhelper service by a json call.

Atm this requires the latest version of skinhelper from Git but I'll make sure to update it on the Kodi repo soon.

Thanks in advance for merging this in!

### CODE REVIEW

**Comment by logi85** [comment]
hi, please let me know when the required version is integrated to kodi repo. I'll test it now. Thx for your work!

**Comment by marcelveldt** [comment]
OK, great! I will do a push to the Kodi repo within a few days. In the meanwhile you can test with the latest skinhelper version from Git. You may also host it temporary on your repo if you want some people to test it

**Comment by marcelveldt** [comment]
skinhelper has been updated on the kodi repo so it should be safe to merge in this PR now.

**Comment by logi85** [comment]
hi, just added requirement to skinhelper but kodi cannot find. Had a look on https://github.com/xbmc/repo-scripts/tree/jarvis and cannot find your addon?

**Comment by marcelveldt** [comment]
the ID of the addon is script.skin.helper.service

It's on the helix repo, which also serves all upper versions of Kodi

**Comment by marcelveldt** [comment]
@logi85 any news about this ?
also, login seems to be broken in the current version, could this be related to any changes at netflix ?

**Comment by logi85** [comment]
hi marcel, could you perhaps split this pr so we have only one pr where all necessary changes integrated to add support ( made a code-review a couple of weeks ago but there are also other changes).

this would help me alot.
also it would be gread that you could add a check that if this is enabled it would be automaticaly disabled if the required things are not installed (pre-check).
otherwise a lot of guys would enable this setting and see only a crashing flix2kodi.

thx!

**Comment by marcelveldt** [comment]
yeah sure, I've done it all in seperate commits. Not sure if I can PR each commit seperately but I'll look after it.

**Comment by marcelveldt** [comment]
@logi85 
Almost impossible to deliver you seperate PR's as it is all tight together and already in one branch.
It should be safe for you to merge this one in.

For your info, these are the changes:

- All artwork and info is fixed for both seasons and episodes
- Fixed the extended artwork retrieval (by using skin helper service)
- Silent auto retry login attempts (to prevent annoying yesno popup)
- Fix view history listings

I have added skinhelper as a dependency btw so users will be able to enable the extended artwork.

**Comment by marcelveldt** [comment]
I have now squashed all commitys into one so it's easier for you to track the changes

**Comment by joaosagrath** [comment]
Hi Marcelveldt! theses changes you made are already to use? Can I manualy copy and replace te actual code? I realy do not understand these, but if is a only copy/paste solves, i'll do the test

**Comment by marcelveldt** [comment]
@logi85 so you want me to quickly solve the conflict ?

**Comment by marcelveldt** [comment]
I've resolved the merge conflict

**Comment by logi85** [comment]
hi, just reviewed your changes, looks good! but one thing. if someone don't want to use skinhelper, it would be automatically installed as it is marked as required. I think it would be better to remove the dependency and check if flag enabled and skinhelper installed on startup.

Do you know a way to start the installtation automatically?

**Comment by marcelveldt** [comment]
Well, most users will have the skinhelper installed as it is used by a lot of skins nowadays.
There is no solid way to install an addon. A command for that is added in Kodi 17 (krypton) but not available in Isengard or Jarvis.

**Comment by logi85** [comment]
ok, you convinced me. I'll merge now.

**Comment by marcelveldt** [comment]
haha, Thanks!

I will keep an eye on the forum if any issues are reported.
Can you bump the version on the repo ?

**Comment by logi85** [comment]
...and uploaded. big thanks for your work!

**Comment by logi85** [comment]
hrhr you were 1 second faster with reply :D

**Pull request merged**
