### PR TITLE
Super browse / hidden categories

### PR DESCRIPTION
**Pull request by badcrc**
A new option for browsing the so-called "hidden" categories of netflix instead of having only Movies and TV Shows.

For the moment the categories are only in english.

### CODE REVIEW

**Comment by logi85** [comment]
hi, please add an option to enable (default disabled) to settings.xml
perhaps you could also query the list of categories from netflix (instead of hard-coded)?
then I'll merge. thx!

**Comment by badcrc** [comment]
Hi,

glad to see you around :) 

I'll add the option to disable it in settings.xml 

Getting them from netflix instead of hardcoded is difficult as I don't really know where people found them,  I'm using a list similar to [this addon](https://chrome.google.com/webstore/detail/super-browse-for-netflix/iejponamigpndjgdmnpelkohnbpancjf?hl=en)  and seems to be based on [reddit posts](https://www.reddit.com/r/technology/comments/3zx1l8/unlock_netflixs_hidden_categories_with_these/) so I don't really know where they come from.

There are called "hidden" for a reason :D

**Comment by badcrc** [comment]
Hi @logi85, I've make the "superbrowsing" optional as requested.

**Comment by logi85** [comment]
thx for your work! merged!

**Pull request merged**
